video_feed: D:\Programming\Python\AI\reid\centroids-reid\data\test_video\cctv.mp4

blacklist: D:\Programming\Python\AI\reid\centroids-reid\data\blacklist

whitelist: D:\Programming\Python\AI\reid\centroids-reid\data\whitelist

yolo_version: yolo_nas_l #assuming pretrained weights are coco

reid_checkpt: D:\programming\Python\AI\reid\centroids-reid\logs\market1501_resnet50_256_128_epoch_120.ckpt
#reid_checkpt: D:\programming\Python\AI\reid\centroids-reid\logs\dukemtmcreid_resnet50_256_128_epoch_120.ckpt

threshold: 0.5

reid: true